name: 'CI: Test'

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: forumapi_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: forumapi_test
      HOST: localhost
      PORT: 5000
      NODE_ENV: development
      ACCESS_TOKEN_KEY: secret_access
      REFRESH_TOKEN_KEY: secret_refresh
      ACCESS_TOKEN_AGE: 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npm run migrate up

      - name: Run tests
        run: npm run test
